version: "3"

services:
  vsftpd:
    image: fauria/vsftpd
    container_name: "vsftpd"
    environment:
      FTP_USER: admin
      FTP_PASS: qwe123
      PASV_ADDRESS: 0.0.0.0
      PASV_MIN_PORT: 21100
      PASV_MAX_PORT: 21000
    volumes:
      - /data/downloads:/home/vsftpd/admin
    ports:
      - '20:20'
      - '21:21'
      - '21100-21110:21100-21110'
    restart: always
    labels:
      - 'traefik.backend=vsftpd'
      - 'traefik.port=21'
      - 'traefik.frontend.rule=Host:ftp.codreamer.online'
